# How Numpy stores arrays

All numpy arrays are actually flat 1D arrays. This can be stored in 2 ways:

- C-Contiguous (like C) - Row Major (default) - so we have rows first, then columns
- F-Contiguous (like fortran) - Column Major

Numpy has a structure called the **strided array interface**, which outlines:

- dtype - the datatype (int, float etc)
- shape - e.g (3,4)
- strides - a tuple (x,y,..) specifying how much to skip on each axes

Dimensions are numbered from 0 to n-1.

When there are more than 2 dimensions - say n dimensions - then row refers to the n-2 dimension, and column to the n-1. The remaining 0-(n-3) dimensions are just used as indexes to get to a specific row-column combination.

Sparse matrices are not supported, this needs scipy.

In [5]:
import numpy as np

# Create a sample 3x3 array of 32-bit integers
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)

# 1. Print standard structural metadata
print(f"Data Type (dtype): {arr.dtype}")
print(f"Array Shape:       {arr.shape}")
print(f"Dimensions (ndim): {arr.ndim}")
print(f"#Elements (Size):    {arr.size}")

# 2. Print memory layout metadata
print(f"Element Size:      {arr.itemsize} bytes")
print(f"Strides:           {arr.strides}") 
# (12, 4) means jump 12 bytes for next row, 4 bytes for next column

# 3. Print complete memory and layout flags
print("\n--- Detailed Memory Flags ---")
print(arr.flags)

Data Type (dtype): int32
Array Shape:       (3, 3)
Dimensions (ndim): 2
#Elements (Size):    9
Element Size:      4 bytes
Strides:           (12, 4)

--- Detailed Memory Flags ---
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## DType Values

You can have 

- int8 to int64 - i1, i2, i4, 18
- similarly uint - u1,u2, u4,u8
- float16-float64 - f2,f4,f8
- complex64 and complex128 - c8, c16
- bool_ - b
- datetime64 - M
- timedelta64 - m
- str_ - U e.g. U10
- bytes - fixed width ASCII byte sequences
- object_ - O - stores pointers to python objects

In [32]:
import numpy as np

ints = np.array([1,2,3], dtype='i2')

floats = np.array([4.2,2.2,3.1], 'f2')

intFromFloats = floats.astype(ints.dtype)

complex = np.array([2+0.j, 3+0.2j], dtype='c8')

display(ints)
display(floats)
display(intFromFloats)
display(complex)

# np.sqrt(np.array([-1,0,1])) - gives error

sqroots = np.sqrt(np.array([-1,0,1], dtype='c8'))  # works fine

display(sqroots.real)


array([1, 2, 3], dtype=int16)

array([4.2, 2.2, 3.1], dtype=float16)

array([4, 2, 3], dtype=int16)

array([2.+0.j , 3.+0.2j], dtype=complex64)

array([0., 0., 1.], dtype=float32)

## Initializing arrays

In [33]:
display(np.zeros((3,3), dtype='f4'))  # 3x3 array of zeros, float32

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [34]:
display(np.ones((2,3), dtype='c8'))  # 2x3 array of ones, float64

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]], dtype=complex64)

In [ ]:
# 2D only - for 3D or higher, use np.diagonal() or np.diagonal(a, offset=0, axis1=0, axis2=1)

display(np.diag(np.array([1,2,3], dtype='i4')))  # 3x3 diagonal matrix with int32

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int32)

In [ ]:
# A 3D array of shape (2, 3, 3)
array_3d = np.ones((2, 3, 3)) # 3D array

# Extracts diagonals across the last two axes (axis1=-2, axis2=-1)
print(np.diagonal(array_3d, axis1=-2, axis2=-1))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 1D - use meshgrid or mgrid for 2D or higher
display(np.arange(10, 20, 2))  # 10 to 20 with step of 2

array([10, 12, 14, 16, 18])

In [44]:
# floating step size makes this float, but use with care, or use linspace instead

display(np.arange(10, 20, 0.5))  # 10 to 20 with step of 2


array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [45]:
display(np.linspace(0, 1, 5, dtype=np.float32))  # 5 evenly spaced numbers from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [47]:
display(np.logspace(0, 100, num=5, base=10.0, dtype=np.float64))  # 5 numbers spaced evenly on a log scale from 10^0 to 10^1000

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [48]:
display(np.meshgrid(np.arange(3), np.arange(4)))  # 2D grid of coordinates

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]))

In [61]:

# 1. mgrid (Fills everything out)
m_grid = np.mgrid[0:5:2, 0:3]
print(m_grid[0].shape)  # Output: (3, 3) -> Fully broadcasted
print(m_grid[1].shape)  # Output: (3, 3) -> Fully broadcasted


(3, 3)
(3, 3)


In [ ]:
# 2. ogrid (Saves memory by keeping it minimal)
o_grid = np.ogrid[0:5:2, 0:3]
print(o_grid[0].shape)  # Output: (3, 1) -> Just a 1D column
print(o_grid[1].shape)  # Output: (1, 3) -> Just a 1D row

(3, 1)
(1, 3)


In [63]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)  # 3x3 array where each element is the sum of its indices

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.random.rand(3, 3)  # 3x3 array of random floats in [0.0, 1.0)

array([[0.81963422, 0.65707846, 0.19510317],
       [0.6775226 , 0.40940955, 0.37473014],
       [0.98415569, 0.3890048 , 0.62030666]])

In [80]:
# Better recommended method
# Initialize the modern generator
rng = np.random.default_rng(seed=42)

# Generate a single integer from 0 to 9 (10 is exclusive)
single_int = rng.integers(low=0, high=10)

# Generate a 1D array of 5 integers between 10 and 50
array_1d = rng.integers(low=10, high=51, size=5)

# Generate a 2x3 matrix of integers
matrix_2d = rng.integers(low=0, high=100, size=(2, 3))

random_floats = rng.random(size=(2, 3))  # 2x3 matrix of random floats in [0.0, 1.0)


display(single_int, array_1d, matrix_2d, random_floats)

np.int64(0)

array([41, 36, 27, 27, 45])

array([[ 8, 69, 20],
       [ 9, 52, 97]])

array([[0.7611397 , 0.78606431, 0.12811363],
       [0.45038594, 0.37079802, 0.92676499]])

In [79]:

# Uniform floats between a custom range, e.g., -5.0 to 5.0
custom_uniform = rng.uniform(low=-5.0, high=5.0, size=5)

# Standard Normal (mean=0, standard deviation=1)
std_normal = rng.standard_normal(size=5)

# Custom Normal (mean=10, standard deviation=2)
custom_normal = rng.normal(loc=10, scale=2, size=5)

# 10 trials, 50% success chance (like flipping 10 coins), repeated 5 times
binomial_samples = rng.binomial(n=10, p=0.5, size=5)

# Lam (lambda) is the known average rate of occurrences (e.g., 3 website hits/minute)
poisson_samples = rng.poisson(lam=3, size=5)

# Scale is the inverse of the rate parameter (1/lambda)
exponential_samples = rng.exponential(scale=2.0, size=5)

display(custom_uniform, std_normal, custom_normal, binomial_samples, poisson_samples, exponential_samples)

array([ 0.68741196, -3.60203002, -3.85469926,  1.68402962, -0.28903794])

array([-1.68286977, -0.33488503,  0.16275307,  0.58622233,  0.71122658])

array([11.58669447,  9.30254986,  9.07529641, 11.71595176,  9.61739135])

array([7, 4, 3, 4, 4])

array([6, 0, 2, 2, 3])

array([1.06203922, 0.60966174, 0.1514774 , 1.0071196 , 4.50375713])

In [82]:
items = ['apple', 'banana', 'cherry', 'date']

# Randomly select 2 items with replacement (items can repeat)
choices = rng.choice(items, size=2, replace=True)

# Randomly shuffle an array in-place
arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)

display(choices, arr)

array(['apple', 'cherry'], dtype='<U6')

array([2, 5, 1, 3, 4])

# Reshaping and Manipulating Arrays


In [101]:
# Reshape existing array
data = np.array([[1, 2],[3, 4]])

newdata = np.reshape(data, (4,1))  # Reshape to 4 rows

anothernewdata = np.ravel(data)  # Flatten the array

newdata[0][0] = 98  # Modify the reshaped array
data[0][1] = 97
anothernewdata[2] = 96  # Modify the flattened array

display(data)
display(newdata)


display(anothernewdata)



# cannot reshape to (5, 1) because the total number of elements (4) does not match the new shape (5)
# display(np.reshape(data, (5, 1)))  # Reshape to 4 rows and 1 column


array([[98, 97],
       [96,  4]])

array([[98],
       [97],
       [96],
       [ 4]])

array([98, 97, 96,  4])

In [102]:
data = np.array([[1, 2],[3, 4]])

newdata = data.flatten()
newdata[0] = 99  # Modify the flattened array

display(data)
display(newdata)

array([[1, 2],
       [3, 4]])

array([99,  2,  3,  4])

In [114]:
data = np.arange(0,5)
column = data[:, np.newaxis]  # Convert to a column vector
column[0] = 99

# expand_dims can be used to add a new axis at a specified position, similar to np.newaxis. 
# For example, np.expand_dims(data, axis=1) would convert the 1D array data into a 2D column vector.

excolumn = np.expand_dims(data, axis=1)
excolumn[1][0] = 88
exrow = np.expand_dims(data, axis=0)
exrow[0][2] = 77

display(data)
display(column)
display(excolumn)
display(exrow)

display(data[2:4, np.newaxis])

array([99, 88, 77,  3,  4])

array([[99],
       [88],
       [77],
       [ 3],
       [ 4]])

array([[99],
       [88],
       [77],
       [ 3],
       [ 4]])

array([[99, 88, 77,  3,  4]])

array([[77],
       [ 3]])

In [121]:
## hstack, vstack, concatenate

data = np.arange(3)

display(np.vstack((data, data, data)))
display(np.hstack((data, data, data)))

coldata = data[:, np.newaxis]  # Convert to a column vector
display(np.vstack((coldata, coldata, coldata)))
display(np.hstack((coldata, coldata, coldata)))

# concatenating multiple row along row axis (0), results in just getting joined up
xdata = np.concatenate((data, data, data), axis=0)  # Concatenate along the first axis (rows)

# concatenating rows along the column axis (1) gives a better output
ydata = np.concatenate((coldata, coldata, coldata), axis=1)  # Concatenate along the second axis (columns)
display(xdata)
display(ydata)



array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

array([[0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

## Vectorized Operations

Numpy performs vectorized operations between arrays. This is where it's real power comes in, eliminating loops and leveraging the memory layout to minimize memory fetches.

Usually binary operations may involve two arrays of the same shape. **Broadcasting** is the approach by which an array may (if it meets the criteria), be adjusted to match the shape of another during an operation. 



In [131]:
## Broadcasting example

one_row = np.arange(1,4)
one_col = one_row[:, np.newaxis]


display(one_row, one_col)

d = np.arange(11,14)
three_array = np.vstack((d, d+10, d+20))
display(three_array)

# broadcast scalars
display(three_array + 2)


# broadcast rows
display(three_array + one_row)

# broadcast columns
display(three_array + one_col)



array([1, 2, 3])

array([[1],
       [2],
       [3]])

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

array([[12, 14, 16],
       [22, 24, 26],
       [32, 34, 36]])

array([[12, 13, 14],
       [23, 24, 25],
       [34, 35, 36]])

In [140]:
# Arithmetric ops

x = np.array([[1,2],[3,4]])
y = x + 4

display(x * 2)


display(x + y)
display(y - x)
display(x * y)
display(y / x)
display(y // x)
display(y ** x)


array([[2, 4],
       [6, 8]])

array([[ 6,  8],
       [10, 12]])

array([[4, 4],
       [4, 4]])

array([[ 5, 12],
       [21, 32]])

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

array([[5, 3],
       [2, 2]])

array([[   5,   36],
       [ 343, 4096]])

In [155]:
# Functions

# Trig - sin, cos, tan, arccos, arcsin, arctan

data = np.pi / np.arange(1,5)

display(data)
display(np.round(np.cos(data), decimals=4))
display(np.arccos(np.cos(data)))

# Hyperbolic
data = np.pi / np.arange(1,5)

display(np.round(np.cosh(data), decimals=4))

# exp, log, log2, log10, sqrt

display(np.sqrt(data))


array([3.14159265, 1.57079633, 1.04719755, 0.78539816])

array([-1.    ,  0.    ,  0.5   ,  0.7071])

array([3.14159265, 1.57079633, 1.04719755, 0.78539816])

array([11.592 ,  2.5092,  1.6003,  1.3246])

array([1.77245385, 1.25331414, 1.02332671, 0.88622693])