# Vectors in $R^n$

A **vector** in $R^n$ is represented by a column matrix:

$$
    \begin{align}
    \vec{x} &= \begin{bmatrix}
           x_1 \\
           x_2 \\
           \vdots \\
           x_n
         \end{bmatrix}
  \end{align}
$$

where $x_1, x_2, \dots, x_n \in R$

**Zero Vector $\vec{0}$** 

$$
    \begin{align}
    \vec{0} &= \begin{bmatrix}
           0 \\
           0 \\
           \vdots \\
           0
         \end{bmatrix}
  \end{align}
$$

**Length of a Vector**

$\Vert \vec{x} \Vert = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}$

**Scalar Multiplication**

Given a real number c, and vector $\vec{x} = \begin{bmatrix}x_1 \\ x_2 \\ \dots \\ x_n \end{bmatrix}$ then :

$$c\vec{x} = \begin{bmatrix}c.x_1 \\ c.x_2 \\ \dots \\ c.x_n \end{bmatrix}$$

This is a "change of scale".

Two vectors are said to be **parallel** if one is a scalar multiple of the other. As a special case, the zero vector $\vec{0}$ is parallel to all vectors.

**Unit Vector**

A vector with length of 1 is called a unit vector. For any vector $\vec{x} \ne \vec{0}$, the unit vector in the direction of $\vec{x}$

$$\frac{\vec{x}}{\Vert \vec{x} \Vert} = \frac{1}{\Vert \vec{x} \Vert} \vec{x} $$

**Vector Addition (and Subtraction)**

Given vectors $\vec{x} = \begin{bmatrix}x_1 \\ x_2 \\ \dots \\x_n\end{bmatrix}$ and $\vec{y} = \begin{bmatrix}y_1 \\ y_2 \\ \dots \\y_n\end{bmatrix}$

$$
    \begin{align}
    \vec{x} + \vec{y} &= \begin{bmatrix}
           x_1 + y_1\\
           x_2 + y_2\\
           \vdots \\
           x_n + y_n
         \end{bmatrix}
  \end{align}
$$

$$
    \begin{align}
    \vec{x} - \vec{y} &= \begin{bmatrix}
           x_1 - y_1\\
           x_2 - y_2\\
           \vdots \\
           x_n - y_n
         \end{bmatrix}
  \end{align}
$$

Notionally, one can visualizing the vector $\vec{x} + \vec{y}$ as the result of "moving" $\vec{y}$ to the end of $\vec{x}$, and drawing the vector 

Vector $\vec{x} - \vec{y}$ should be thought of as the vector to be added to $\vec{y}$ to get $\vec{x}$.



## Properties of Vector Algebra (Exercise 1.12)

For all $\vec{x}$, $\vec{y}, \vec{z}$ in $R^n$, and c,d in $R$:

(a) $\vec{x} + \vec{y} = \vec{y} + \vec{x}$ 

(b) $\vec{x} + (\vec{y} + \vec{z}) = (\vec{x} + \vec{y}) + \vec{z}$ 

(c) $\vec{0} + \vec{x} = \vec{x}$

(d) For each $\vec{x}$ there exists $\vec{-x}$ s.t. $\vec{x} + \vec{-x} = \vec{0}$

(e) $c(d(\vec{x})) = (cd) \vec{x}$

(f) $(c + d)(\vec{x})) = c \vec{x} + d \vec{x}$

(g) $c(\vec{x} + \vec{y})) = c (\vec{x} + \vec{y})$

(h) $1\vec{x} = \vec{x}$

**Prove (ex 1.13): $0\vec{x} = \vec{0}$**

$0\vec{x} = (0 + 0)\vec{x} = 0\vec{x} + 0 \vec{x}$, using property (f)

Using the additive inverse of $0\vec{x}$, $-0\vec{x}$ using property (d), and adding it to both sides, we get:

$0 = (0\vec{x} + 0 \vec{x}) + -0\vec{x}$, using property (f)

Using property (b), we can rearrange the brackets:

$0 = 0\vec{x} + (0 \vec{x} + -0\vec{x})$, using property (f)

Using property (d), we get:
$0 = 0\vec{x} + 0$, 

$0 = 0 + 0\vec{x}$, using property (a)

Hence,
$0 = 0\vec{x}$ using property (c)

**Corollary: $(-1)\vec{x} = \vec{-x}$**

$0\vec{x} = 0$ => $(1 + -1)\vec{x} = 0 => 1\vec{x} + (-1)\vec{x} = 0 => \vec{x} + (-1)\vec{x} = 0$

Adding $\vec{-x}$ on both sides:

$\vec{-x} + (\vec{x} + (-1)\vec{x}) = 0 + \vec{-x}$

$(\vec{-x} + (\vec{x}) + (-1)\vec{x} = \vec{-x}$

$0 + (-1)\vec{x} = \vec{-x}$

$(-1)\vec{x} = \vec{-x}$

**Corollary: Additive inverse is unique**

Let $\vec{x} + \vec{v} = 0$. Adding $-\vec{x}$ to both sides

$\vec{-x} + \vec{x} + \vec{v} = -\vec{x}$

$\vec{0} + \vec{v} = -\vec{x}$

i.e. $\vec{v} = -\vec{x}$












## Exercise 1.1

In [15]:
# Exercise 1.1-1 

import sympy as s

x = s.Matrix([2,3])
y = s.Matrix([-1,1])


display(x, x.norm(), x/2, x/x.norm())

display(x + y, s.Rational(1,2)*(x + y))



Matrix([
[2],
[3]])

sqrt(13)

Matrix([
[  1],
[3/2]])

Matrix([
[2*sqrt(13)/13],
[3*sqrt(13)/13]])

Matrix([
[1],
[4]])

Matrix([
[1/2],
[  2]])

In [8]:
import numpy as np
from numpy.linalg import norm

import numpy as np

# These 3 points are given
u = np.array([1,2,1])
v = np.array([2,4,3])
w = np.array([3,1,5])

# we have to find all possible points for forming a parallelogram. Here is one example, using the diagonal uw:

p = u + (w - v)

print(p, norm(u-v), norm(p-w), norm(w-v), norm(p-u))


# diagonal uv
q = u + (v - w)
print(q, norm(u-w), norm(q-v), norm(v-w), norm(q-u))

# diagonal vw
r = v + (w - u)
print(r, norm(v-u), norm(r-w), norm(w-u), norm(r-v))



[ 2 -1  3] 3.0 3.0 3.7416573867739413 3.7416573867739413
[ 0  5 -1] 4.58257569495584 4.58257569495584 3.7416573867739413 3.7416573867739413
[4 3 7] 3.0 3.0 4.58257569495584 4.58257569495584


# Ex. 1.3 Polygon Vertices

Origin is at center of a regular polygon of n sides.

a) Sum of vectors to each vertex = 2 

The simplest answer is to say: the angle between the vectors from the center to each vertex is $2\pi/n$ and all vectors are the same length. Starting with one vector, if we move the next vector to its head, we have an exterior angle of $2\pi/n$ which implies the sum of all the vectors angles adds up to 2 pi, forming a regular polygon i.e. ending back at the tail of the first vector. So the sum of the vectors from center to the vertices is zero.

b) Sum of vectors from one vertex to the others:

Number the vertices 1,2,...n, and let the vertex 1 be the one from which vectors $v_1, v_2, v_3, v_n$ are drawn (v_1 = 0). Let O be the center, and the vector from O to vertex i be called $\vec{p_i}$.

Then : $\vec{v_i} = \vec{p_i} - \vec{p_1}$

Summing, we get $Sum = (\text{sum of vectors from origin}) -n \vec{p_1} = \vec{0} - n \vec{p_1} = -n \vec{p_1}$



# Ex. 1.4 /1.5 Triangle, Quadrilateral - line joining midpoints

Given triangle ABC, let M and N be the midpoints of AB and AC, respectively. Prove $\vec{MN} = 1/2\vec{BC}$

Proof: 

Let AB = $\vec{x}$, AC = $\vec{y}$, and BC = $\vec{y} - \vec{x}$.

Hence : AM = $1/2\vec{x}$, AN = $1/2\vec{y}$ and $\vec{MN} = 1/2\vec{y} - 1/2 \vec{x} = 1/2\vec{BC}$


Given a quadrilateral ABCD, the lines joining the midpoints form a parallelogram. Let M,N,O,P be midpoints of AB, BC, CD, DA respectively.

This follows because :

AC splits the quadrilateral into two triangles : ABC abd ADC, with a common base AC. Then $\vec{MN} = 1/2 \vec{AC} = 1/2 \vec{PO}$

And similarly, we get $\vec{NO} = 1/2 \vec{BD} = \vec{MP}$


# Ex 1.6 

Let ABC be a triangle, with points D, E such that : len(AD) = 2/3 len(AB), and len(CE) = 2/5 len(CB).  If Q, is the intersection of CD and AE,  find the ratio len(AQ)/len(AE).

Let AB = u, and AC = v.

AE = v + 2/5 (u-v) = 3/5 v + 2/5 u.
AQ = cAE = c(3/5v + 2/5 u) = c3/5v + c2/5u

But also, AQ = AC + sCD = v + s(2/3u - v) = 2/3su + (1-s)v

Hence, s2/3 = c2/5 i.e. s = 3/5c

also, c3/5 = 1-s = 1-3/5c. Hence c = 5/6 and s = 1/2 i.e. Q is midpoint of CD.

We can also do this by **mass-points**:

Let A = 1, then B = 2, and C = 3. Weight at E = 5. AQ:QE = 5:1 i.e. AQ/AE = 5:6

Also, weight at D = 3 = weight at C => Q is midpoint of CD.

# Ex 1.8 - Centroid of a triangle

Let x,y,z represent points of a triangle, the midpoints are 1/2(x + y) and 1/2(x + z).

c = y + s(1/2(x + z) - y) = s/2x + (1-s)y + s/2z
d = t/2x + t/2y + (1-t)z

equating: 
t/2 = 1-s i.e s = 1-t/2
Also t = s
s = 1-s/2 or 3s/2 = 1 or s = 2/3 = t.

c = 1/3(x + y + z)


# Ex 1.9 - Points on a line, and in a Triangle

$\vec{u}$ and $\vec{v}$ are two vectors.

$\vec{x} = s\vec{u} + t\vec{v}$, s + t = 1, 

Then,

$\vec{x} = \vec{v} + s({\vec{u} - \vec{v}})$

Thus, x is a **point on the line from v to u**. 
s = 0 => x = v
s = 1 => x = u
s < 0 => point away from v, opp to side of u
s > 1 => point away from u, opp to side of v

what happens if 0 < s + t < 1, both s and t positive? In fact, think of s & t as coordinates given axes u & v. 
Then if s and t are positive, these are points between vectors u and v. In addition, if s + t < 1, these are within the triangle formed by u and v.
if s + t > 1, these are outside the triangle. Similarly we can conclude about other combinations of s and t.


Similarly, let $\vec{u}, \vec{v} and \vec{w}$ be three vectors.


$\vec{x} = r\vec{u} + s\vec{v} + t\vec{w}$, r + s + t = 1.

Then:

$\vec{x} = \vec{u} + s(\vec{v} - \vec{u}) + t(\vec{w} - \vec{u})$, 

Note that s+t = 1 represents a point on the line joining head of v and w just like above. And in fact, taking u as the origin,
s and t act like coordinates along the vectors (v - u) and (w-u) - thus we have 0 < s + t < 1 inside the triangle, s > 0, t > 0.
But then, r = 1 - s - t > 0, i.e. inside the triangle, r,s and t are all greater than zero.










# Ex 1.10 - Linear combination rules

If $\vec{x}$ and $\vec{y}$ are non-parallel vectors.

**Prove: $s\vec{x} + t \vec{y} = 0$ => s,t = 0.**

Note that x, y are not zero (as zero is parallel to every vector). 

Assume s and t and non-zero.

But then: $\vec{x} = -(t/s)\vec{y}$ which implies the vectors are parallel, a contradiction.

**Prove: $a\vec{x} + b \vec{y} = c\vec{x} + d \vec{y}$ => a = c, b = d**

Subtracting, we get 
$(a-c)\vec{x} + (b-d)\vec{y} = 0$

From the first result, it follows that a-c = 0, b-d = 0.



# Vectors and linear combinations - GS 1.1

A **vector** is represented by a column matrix:

$
  \begin{align}
    v &= \begin{bmatrix}
           1 \\
           2 \\
           \vdots \\
           3
         \end{bmatrix}
  \end{align}
$


A **linear combination** of vectors combines scalar multiplication of vectors + addition of vectors to create a new vector

$
  \begin{align}
    2 \begin{bmatrix} 4 \\ 1  \end{bmatrix} + 
    3 \begin{bmatrix} 2 \\ -1 \end{bmatrix} = 
    \begin{bmatrix} 14 \\ -1 \end{bmatrix}
  \end{align}
$


A **matrix** is a collection of column vectors, and matrices with the right shapes can be multiplied. In general an **m by n** matrix has m rows with n columns. 


$
\begin{equation}
\left[ \begin{array}{rrrr} 4 & 2 \\ 1 & -1 \end{array}\right] \text{ ... a 2x2 matrix with 2 column vectors}
\end{equation}
$

The linear combination above can be expressed (using matrix multiplication) as:

$
\begin{equation}
\left[ \begin{array}{rrrr} 4 & 2 \\ 1 & -1 \end{array}\right] \left[ \begin{array}{rrrr} 2 \\ 3 \end{array}\right] = \left[ \begin{array}{rrrr} 14 \\ -1 \end{array}\right]
\end{equation}
$


A set of vectors are **linearly independent** if no one vector can be expressed as a linear combination of any of the others. 

The **identity matrix** leaves any vector unchanged on multiplication:

$
  \begin{align}
     \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} v = v
  \end{align}
$


## Problem Set GS1.1

In [4]:

# (3.4)

import numpy as np

v = np.array([4,1]).reshape(2,1)
w = np.array([-2, 2]).reshape(2,1)

print(v - w, '\n')
print(2*v)

[[ 6]
 [-1]] 

[[8]
 [2]]


## Problems: Linear Combinations of Vectors & Geometry (GS1.1. 18-23)

18. What is : cv + dw, where c + d = 1: This is on the diagonal joining the tips of v and w. When c/d are positive this is within the parallelogram. But -v + 2w is beyond tip of w, and 2v - w is beyond tip of v.

19. if 0 <= c <= 1, and 0 <= d <= 1, then 0 <= c+d <= 2. We know c+d=2 (u + w) is the far end of the parallelogram, and c+d = 0 is the origin, c+d =1 is in the middle. So all these points are within the parallelogram.

If 0 <= c, and 0 <= d is the "cone" between v and w extended to the whole plane.

20. Given 3 vectors u,v,w the tips of the vectors form a triangle (usually). 1/2 u + 1/2v is the midpoint of the side joining u and v. 1/3 u + 1/3 v + 1/3 w is the centroid of the triangle, within the triangle.

given cu + dv + ew, what are the conditions on c,d,e for points within the triangle? And: c + d + e = 1 and c,d,e >= 0. 

21. Given 3 vectors u,v,w, the vectors v-u, u-w, w-v correspond to the triangle formed by the 3 vectors. The sum of these vectors is the zero vector, i.e. they are not linearly independent - they are in the same plane.

22. For 20: if c + d + e <= 1, and c,d,e >=0, this is the pyramid between the origin and the triangle. if c+d+e >= 1, these are points beyond the triangle.


# Lengths and Angles From Dot Product






Let v and w be two vectors:


$
  \begin{align}
    \vec{v} &= \begin{bmatrix}
           v_1 \\
           v_2 
         \end{bmatrix}
  \end{align}
$


$
  \begin{align}
    \vec{w} &= \begin{bmatrix}
           w_1 \\
           w_2 
         \end{bmatrix}
  \end{align}
$


The **dot product** of the two vectors: $\vec{v} \cdot \vec{w} = v_1 w_1 + v_2 w_2$

The **length or norm of vector** of the two vectors: $\Vert \vec{v} \Vert = \sqrt{\vec{v} \cdot \vec{v}}$

The **angle** between vectors: $\cos{\theta} = \frac{\displaystyle \vec{v} \cdot \vec{w}}{\displaystyle \Vert \vec{v} \Vert \Vert \vec{w} \Vert}$

**Schwarz Inequality**

Follows from cosine definition also:

$| \vec{v} \cdot \vec{w} |  \le \Vert \vec{v} \Vert \Vert \vec{w} \Vert$


**Triangle Inequality**

$ \Vert \vec{v} + \vec{w} \Vert  \le \Vert \vec{v} \Vert + \Vert \vec{w} \Vert$


A **unit vector** has length = 1.

$ \Vert \vec{u} \Vert  = 1$

$ \vec{u} = \frac{\displaystyle v}{\displaystyle \Vert \vec{v} \Vert}$




In [2]:
import numpy as np
import math

def norm(v):
    return math.sqrt(np.dot(v,v))

def costheta(v1, v2):
    return np.dot(v1, v2) / (norm(v1)*norm(v2))

def theta(v1, v2):
    return math.degrees(math.acos(costheta(v1,v2)))


In [21]:
# Problem set 1.2

## 1

import numpy as np
u = np.array([-.6, .8])
v = np.array([4.0,3.0])
w = np.array([1,2])

print(round(np.dot(u,v), 10))
print(np.dot(u,w))
print(np.dot(u, v+w))
print(np.dot(w,v))



0.0
1.0
1.0000000000000002
10.0


5. Find all vectors (w1, w2) perpendicular to v = (2, -1)

2w1 - w2 = 0

w1 = 1/2 w2

e.g. (1, 2), (2, 4) etc.

6.(b) : All vectors perp to (1,1,1) lie in a plane : Let (x,y,z) represent a perp vector. Then x + y + z = 0 for all these vectors. 
Note that (0,0,0) lies in the plane x + y + z = 0, and of course the point (x,y,z) does also for any vector (x,y,z). 
Thus the entire vector lies in the plane.

6.(c) : All vectors perp to (1,1,1) and (1,2,3) lie in a single line: Let (x,y,z) rep such a vector. Then x + y + z = 0, and x + 2y + 3z = 0.

Equation of line: y = 2z, x = z, 2x = 2z. 2x = y = 2z or x/1 = y/2 = z/1 is the equation of the line.



In [12]:
# 7.b,c,d

print(theta([2,2,1], [2,-1,2]))
print(round(theta([1, math.sqrt(3)], [-1, math.sqrt(3)]), 10))
print(theta([3,1], [-1,-2]))


63.612200038757
60.0
135.0


11. Given a vector v in 3d space, find all vectors w where v.w is less than zero:

Ans: one-half of 3d space forms vectors w such that v.w is less than zero. 

12. With v = (1,1) and w = (1, 5) choose a number ¢ so that w — cv is perpendicular to v. Then find the formula for c starting from any nonzero v and w.

w - cv = (1-c, 5-c)

v.(w -cv) = 1-c + 5 -c = 0 => c = 3.

In generate v - (v1, v2), w = (w1,w2)

w - cv = w1-cv1, w2-cv2

v.(w-cv) = v1.(w1-cv1) + v2.(w2-cv2) = v.w - c(v1^2 + v2^2) = 0
c = v.w/v.v



13. Non-zero vectors u,v,w perpendicular to (1,1,1,1) and each other.

(1,1,-1,-1) 

(1,-1,1,-1) 

(1,-1,-1,1) 



In [16]:
# 16.

a = costheta([1,0,-1],[1,0,0])
b = costheta([1,0,-1],[0,1,0])
c = costheta([1,0,-1],[0,0,1])

print(a*a + b*b + c*c)

0.9999999999999998
