# Linear Transformation 
The link of linear algebra with differentiation is that we view differentation as the way to get the best linear approximation to a function at a given point.

<div class="alert alert-block alert-info">

A <b>linear transformation</b> or a <b>linear map</b> is a function 

$T: R^n \to R^m$ if it meets the following condition

- $T(\vec{v} + \vec{w}) = T(\vec{v}) + T(\vec{w})$
- $T(c\vec{v}) = cT(\vec{v})$
</div>

Notes: 

y = mx + b is not linear by this definition, we need to use y = mx only.

Examples for $T: R \to R$:

$T(x) = x$

$T(x) = 0$

$T(x) = 5x$

Following are not linear:

$T(x) = x + 1$

$T(x) = |x|$





Examples for $T: R^n \to R$:

$T(\vec{x}) = x_1$ if $\vec{x}=\begin{bmatrix} x_1 \\ x_2 \\ \dots \\ x_n \end{bmatrix}$

For any vector $\vec{a}$:

$T(\vec{x}) = x \cdot a$ is a linear map.


Examples for $T: R^2 \to R^2$:

Reflection on x axis:

$T(\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}) = \begin{bmatrix} x_1 \\ -x_2 \end{bmatrix}$

Rotation by $\pi/2$

$T(\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}) = \begin{bmatrix} -x_2\\ x_1 \end{bmatrix}$



# Matrices and Linear Maps

To a linear map, $T: R^n \to R^m$ we associate an **mxn** matrix, called the **standard matrix** of T which represents the mapped value of each of the standard basis vectors of $R^n$

Assume $e_1, e_2, \dots, e_n$ are the basis vectors for $R^n$, Then the matrix $\begin{bmatrix}T(e_1) & T(e_2) & \dots & T(e_n)\end{bmatrix}$ is the standard matrix of T. 

Some examples: 

For reflection in $R^2$, the standard matrix is $\begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}$

For rotation by $\pi/2$ in $R^2$, the standard matrix is $\begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}$

## Proof that The value of T for standard basis vectors completely define T?

Assume we know $T(e_1), T(e_2), \dots, T(e_n)$. The given any $\vec{x} \in R$, we can express it as a linear combination of the standard basis vectors:

$\vec{x} = \begin{bmatrix} x_1 \\ x_2 \\ \dots \\ x_n\end{bmatrix} = x_1 e_1 + x_2 e_2 + \dots + x_n e_n$

Then, we have:

$T(\vec{x}) = T(x_1 e_1 + x_2 e_2 + \dots + x_n e_n) = T(x_1 e_1) + T(x_2 e_2) + \dots + T(x_n e_n) = x_1T(e_1) + x_2T(e_2) + \dots + x_n T(e_n)$

Thus, given the value of T at the standard basis vectors, we can get the value of T for any vector in the vector space.


Example : Rotation in $R^2$

Let A = $\begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}$ be the standard matrix for function T.

Then 
$$
\begin{align}
T(\vec{x}) &= x_1\begin{bmatrix} 0 \\ 1 \end{bmatrix} + x_2\begin{bmatrix} -1 \\ 0 \end{bmatrix} 
            &= \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}\begin{bmatrix}x_1 \\ x_2\end{bmatrix}
            &= \begin{bmatrix} -x_2 \\ x_1  \end{bmatrix}
\end{align}
$$

# Matrix Multiplication by a vector - Column Vector view

Based on above, we can define matrix multiplication of a matrix A by a vector $\vec{x}$ as a linear combination of the column vectors of A, where each column vector is an m-component vector describing the vector to which the corresponding $R^n$ basis vector maps in $R^m$. If A is an m x n matrix, this implies that x must be an n-component vector.

Assuming $A = \begin{bmatrix}\vec{a_1} & \vec{a_2} & \dots & \vec{a_n} \end{bmatrix}$, and $\vec{x} = \begin{bmatrix} x_1 \\ x_2 \\ \dots \\ x_n\end{bmatrix}$ we get:

$A\vec{x} = x_1\vec{a_1} + x_2\vec{a_2} + \dots + x_n\vec{a_n}$ - note that the result is a vector in $R^m$, because each of $a_i$ vectors is an m-component vector.

# Matrix Multiplication by a vector - Row Vector view

We can also consider the vector A to be comprised on m n-component **row** vectors. 

$A = \begin{bmatrix} A_1 \\ A_2 \\ \dots \\ A_m\end{bmatrix}$ 

Then we see that we can also express the multiplication by vector $\vec{x}$ as follows:

$A\vec{x} = \begin{bmatrix} A_1 \cdot \vec{x} \\ A_2 \cdot \vec{x} \\ \dots \\ A_m \cdot \vec{x}\end{bmatrix}$

This is a strange fact that the linear combination of column vectors, vs the dot product with row vectors are two completely equivalent ways to view the same operation of multiplication.

# Matrix Multiplication by another matrix

A natural extension of matrix multiplication is to multiply an mxn matrix A with an nxp matrix B, resulting in an mxp matrix. 

$A = \begin{bmatrix} A_1 \\ A_2 \\ \dots \\ A_m\end{bmatrix}$  and 

$B = \begin{bmatrix}a_1 & a_2 & \dots & a_p \end{bmatrix}$ where $a_1, a_2, \dots, a_p$ are n-component column vectors.

Then,

$AB = \begin{bmatrix} 
        A_1 \cdot a_1 & A_1 \cdot a_2 & \dots & A_1 \cdot a_p \\
        A_2 \cdot a_1 & A_2 \cdot a_2 & \dots & A_2 \cdot a_p \\
        \dots \\
        A_m \cdot a_1 & A_m \cdot a_2 & \dots & A_m \cdot a_p      
      \end{bmatrix}
$

As is obvious, this is an m x p matrix, with m rows (as the result is in $R^m$) and p columns, one for each column vector in matrix P.

The resultant matrix is a function from $R^p$ to $R^m$, as opposed to the matrix A which is a function from $R^n$ to $R^m$. 


# Matrix Multiplication as function composition

The mxn matrix A represents a function $T: R^n \to R^m$, and the nxp matrix B represents a function $S: R^p \to R^n$. The matrix multiplication represents a function formed by composition: $T \circ S$, from $R^p$ to $R^m$. Thus assuming $\vec{p}$ is a vector in $R^p$, then :

$AB\vec{p} = T \circ S(\vec{p}) = T(S(\vec{p})) = \vec{m}$

Basically we map a vector p in $R^p$ to a vector m in $R^m$. 

Because matrix multiplication is basically composition, the following facts follow:

a) Matrix multiplication is non-commutative

b) Matrix multiplication is associative i.e. A(BC)x = (AB)Cx



## Proof Outline that Matrix Multiplication is equal to composition

Based on definitions above, let A be the m x n standard matrix for function T, and B be the n x p matrix for function S. 

We have to show that $AB\vec{x} = T \circ S(\vec{x})$

Recall $A = \begin{bmatrix}T(e_1) & T(e_2) & \dots & T(e_n)\end{bmatrix}$

Similarly, $B = \begin{bmatrix}b_1 & b_2 & \dots & b_p \end{bmatrix} = \begin{bmatrix}S(e_1) & S(e_2) & \dots & S(e_p)\end{bmatrix}$ 

Now, for any j = 1 to p, 

$T \circ S(\vec{e_j}) = T(S(e_j)) = T(b_j) = Ab_j$

But $Ab_j$ is the jth column of the matrix AB, i.e.

$AB = \begin{bmatrix}T \circ S(e_1) & T \circ S(e_2) & \dots & T \circ S(e_p)\end{bmatrix}$

Thus AB is the standard matrix of the function $T \circ S$

## Linear map $T:R^n \to R$ is of the form $T(\vec{x}) = \vec{a} \cdot \vec{x}$

Any linear map is defined by the values at the basis vectors. 

Hence if A is the standard matrix of T, then $A = \begin{bmatrix} T(e_1) & T(e_2) & \dots & T(e_n)\end{bmatrix}$ 

Also, $A\vec{x} = \begin{bmatrix}x_1T(e_1) + x_2T(e_2) + \dots + x_n T(e_n) \end{bmatrix} = \begin{bmatrix}T(\vec{x})\end{bmatrix}$

If we take $\vec{a} = A^T = \begin{bmatrix} T(e_1) \\ T(e_2) \\ \dots \\ T(e_n)\end{bmatrix}$, then we see that $\vec{a} \cdot \vec{x} = T(\vec{x})$

## Matrix for Rotation in $R^2$

Assume we rotate the $R^2$ plane by angle $\theta$

Then $T(e_1) = \begin{bmatrix} \cos{\theta} \\ \sin(\theta) \end{bmatrix}$ and $T(e_2) = \begin{bmatrix} -\sin{\theta} \\ \cos(\theta) \end{bmatrix}$

Thus the standard matrix is 
$\begin{bmatrix}\cos{\theta} & -\sin{\theta} \\ \sin(\theta) & \cos{\theta}\end{bmatrix}$

In [26]:
# Exercises

import numpy as np
from numpy.linalg import norm

import numpy as np

# These 3 points are given
u = np.array([1,2,1])
v = np.array([2,4,3])
w = np.array([3,1,5])

# we have to find all possible points for forming a parallelogram. 

vu = u - v
vw = w - v

p = w + u - v


print(vu, vw, norm(vu), norm(vw), p, norm(p-w), norm(p-u))


uv = v - u
uw = w - u

q = w + v - u

print(uv, uw, norm(uv), norm(uw), q, norm(q-v), norm(q-w))

wv = v - w
wu = u - w

r = u + v - w

print(wv, wu, norm(wv), norm(wu), r, norm(r-v), norm(r-u))

print(u + v - w)
print(u + w - v)
print(v + w - u)



[-1 -2 -2] [ 1 -3  2] 3.0 3.7416573867739413 [ 2 -1  3] 3.0 3.7416573867739413
[1 2 2] [ 2 -1  4] 3.0 4.58257569495584 [4 3 7] 4.58257569495584 3.0
[-1  3 -2] [-2  1 -4] 3.7416573867739413 4.58257569495584 [ 0  5 -1] 4.58257569495584 3.7416573867739413
[ 0  5 -1]
[ 2 -1  3]
[4 3 7]


In [27]:
import sympy as s

v1 = s.Matrix([1,2,1])
v2 = s.Matrix([2,3,1])
cross_result = v1.cross(v2)
cross_result

Matrix([
[-1],
[ 1],
[-1]])